##
## EPITECH PROJECT, 2024
## B-CNA-410-REN-4-1-groundhog-maxence.largeot
## File description:
## Makefile
##

SRC	=	src/main.py

NAME	=	trade

all:	$(NAME)

$(NAME):
	@ chmod 777 $(SRC)
	@ ln -s src/main.py $(NAME)

clean:

fclean:	clean
	rm -Rf trade

re: fclean all

tests_run:

.PHONY: all clean fclean re